### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by Robinlovelace** [biodar/bioAtlas#1]
Opened just to say: this is awesome! Great new use case of the technology.

**Comment by Katatrepsis** [comment]
Let's hope all the issues are just awesomeness :-)

**Comment by layik** [comment]
Thanks @Robinlovelace and @Katatrepsis. It is promising so far. Though eAtlas needs upstream changes/release(s) to incorporate even this basic trigonometry (no z yet), the beta release has an issue and should work out of the box. But for any real pointcloud it does need upstream (hopefully minor) updates. 

More in new tickets and issues. Just talking to myself here, will do all I can to utilize the power of clients as .h5 is compact and CPU/GPU is cheaper than "transport". But there is always the possibility to fall back on servers doing more.

Attached is the 2D "rays" of a sample .h5 using jsfive in eAtlas.
<img width="100%" alt="Screenshot 2021-06-16 at 23 19 17" src="https://user-images.githubusercontent.com/408568/122357998-2202b900-cf4c-11eb-9e53-112f8dd28b07.png">

**Comment by layik** [comment]
I think we can close this. It was a great issue, thanks both.
