### ISSUE TITLE
Make bioAtlas a geoplumber app

### ISSUE THREAD

**Issue by layik** [biodar/bioAtlas#2]
- [x] scaffolding (plumber.R) etc
- [x] Docker file + run script etc
- [x] etc ?

**Comment by Robinlovelace** [comment]
Sounds like a good plan to me. Would be good to get a minimal input dataset at low resolution (1km pixels and 100m height bands?) for demo purposes.

**Comment by layik** [comment]
Sure. So the points are 600m apart. I think that is low res enough? What you see deployed at https://biodar.github.io/bioAtlas/ should be so. What I also do is clip (as discussed in emails) everything beyond 50km radius and also reflectivity (guessing biological targets) so we endup with some ~1,500 points out of 180k. 

I was like, could I see some pattern shifting (insects travelling 600m distance in X time) but I might have to go R.data.table to process the total Examples we have hence this issue.

**Comment by Robinlovelace** [comment]
![Peek 2021-07-12 12-45](https://user-images.githubusercontent.com/1825120/125282301-22099500-e30f-11eb-8e2f-4e4dd430180b.gif)

Great to see the latest version up and deployed for public use!  https://biodar.github.io/bioAtlas/

**Comment by layik** [comment]
Try changing the point sizes and eAtlas colours are not best coded, so pick the 2nd from the right and should see this:
<img width="1300" alt="Screenshot 2021-07-12 at 12 49 54" src="https://user-images.githubusercontent.com/408568/125282835-b70c8e00-e30f-11eb-8108-2fd4d3b0b350.png">

Then we rename the legend to show Purple as "Butterfly" etc.

**Comment by layik** [comment]
https://blog.aba.org/2011/04/following-bird-migration-with-dopplar.html

**Comment by layik** [comment]
Separate ticket for Dockerbuild if need be
