### ISSUE TITLE
Deploy on JASMIN Server

### ISSUE THREAD

**Issue by layik** [biodar/bioAtlas#3]
Based on #2 

- [x] install Docker (fully reprex please or documented)
- [x] document changes on server on private repo
- [x] etc ?

**Comment by layik** [comment]
Pending #2 & #4

**Comment by layik** [comment]
Understanding changes to GitHub Docker Registry API etc might not be worth the while. We might have to get a round builds happening on GitHub by doing it on our servers using action push etc.

**Comment by layik** [comment]
Compose written and it is functional for now. cc #8

**Comment by Robinlovelace** [comment]
:tada:
